---
language: python
python:
  - 3.5
  - 3.6
  - nightly
install:
  - pip install flake8 flake8-import-order doc8 Pygments
  - python setup.py sdist
  - pip install dist/localstripe-*.tar.gz
script:
  - flake8 .
  - doc8 README.rst
  - python3 -m localstripe &
  -  # wait for server to be up:
    timeout=5; while [ $((timeout--)) -ge 0 ]; do
      nc -z -w 1 localhost 8420; r=$?; [ $r -eq 0 ] && break; sleep 1;
    done; return $r
  - ./test.sh
