---
language: python
python:
  - 3.7
  - 3.8
  - 3.9-dev
  # Python nightly currently disabled because of compilation issues
  # - nightly
install:
  - pip install flake8 flake8-import-order doc8 Pygments
  - python setup.py sdist
  - pip install dist/localstripe-*.tar.gz
script:
  - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi
  - doc8 README.rst
  - python3 -m localstripe &
  -  # wait for server to be up:
    timeout=5; while [ $((timeout--)) -ge 0 ]; do
      nc -z -w 1 localhost 8420; r=$?; [ $r -eq 0 ] && break; sleep 1;
    done; return $r
  - ./test.sh
