trigger:
  branches:
    include:
      - qp-mock-master
pr:
  branches:
    include:
      - qp-mock-master

variables:
  azureSubscription: 'QuadPay PAYG (4225a42d-cebe-4062-a1a1-7ce5954c40c6)'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build & Push
    jobs:
      - job: Build
        displayName: Build & Push
        workspace:
          clean: all
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              repository: mocks/localstripe
              command: build
              containerRegistry: Azure quadpay container registry
              tags: |
                latest
                $(Build.BuildNumber)
          - ${{ if or( eq(variables['Build.SourceBranch'], 'refs/heads/qp-mock-master'), eq(variables['Build.Reason'], 'Manual') ) }}:
              - task: Docker@2
                displayName: Push docker image
                inputs:
                  repository: mocks/localstripe
                  command: push
                  containerRegistry: Azure quadpay container registry
                  tags: |
                    latest
                    $(Build.BuildNumber)
