trigger:
  branches:
    include:
      - qp-mock-master
pr:
  branches:
    include:
      - qp-mock-master

variables:
  azureSubscription: 'QuadPay PAYG (4225a42d-cebe-4062-a1a1-7ce5954c40c6)'

stages:
  - stage: Build
    displayName: Build & Push
    jobs:
      - job: Build
        displayName: Build & Push
        workspace:
          clean: all
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              repository: mocks/localstripe
              command: buildAndPush
              containerRegistry: Azure quadpay container registry
              tags: |
                latest
                $(Build.BuildNumber)
