trigger:
  branches:
    include:
      - qp-mock-master
pr:
  branches:
    include:
      - qp-mock-master

parameters:
  - name: regions
    displayName: Enabled Regions
    type: object
    default:
      - eastus
  - name: environments
    displayName: Enabled Environments
    type: object
    default:
      - development

variables:
  - template: ../../build/variables.yaml
  - name: service-name
    value: localstripe
  - name: dockerfile
    value: $(System.DefaultWorkingDirectory)/Dockerfile

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build, Push and Publish
    jobs:
      - job: Build
        displayName: Build, Push and Publish
        workspace:
          clean: all
        steps:
          - template: ./build/templates/setup.yaml
          - template: ./build/templates/build.yaml

  # Deploy to Development
  - template: ./build/templates/deploy.yaml
    parameters:
      dependsOn:
        - Build
      regions: ${{ parameters.regions }}
      environment: development
      group: ci
      condition: >
        and(
          succeeded(),
          or(
            eq(variables['build.sourceBranch'], 'refs/heads/qp-mock-master'),
            eq(variables['Build.Reason'], 'Manual')
          )
        )
