replicaCount: 2

image:
  repository: quadpay.azurecr.io/mocks/localstripe
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
   readOnlyRootFilesystem: false # We have to write a python pickle file to maintain state
   runAsNonRoot: true
   runAsUser: 1000

service:
  type: ClusterIP
  port: 80

redis:
  sidecar:
    enabled: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: stripe-mock.quadpay.xyz
      paths:
        - /
  tls:
    - hosts:
        - stripe-mock.quadpay.xyz
      secretName: stripe-mock-tls

resources:
   limits:
     cpu: 12000m
     memory: 64Gi
   requests:
     cpu: 2000m
     memory: 8Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
