replicaCount: 1

image:
  repository: quadpay.azurecr.io/mocks/localstripe
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
   readOnlyRootFilesystem: false # We have to write a python pickle file to maintain state
   runAsNonRoot: true
   runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: stripe-mock.quadpay.xyz
      paths:
        - /
  tls:
    - hosts:
        - stripe-mock.quadpay.xyz
      secretName: stripe-mock-tls

resources:
   limits:
     cpu: 100m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
